env:
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
extends: 
  - airbnb-base
  - airbnb-typescript
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
root: true
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
rules:
  no-console: 0
  react/jsx-filename-extension: 0
  max-len:
    - error
    - code: 120
  import/extensions:
    - error
    - ignorePackages
    - ts: always
    - js: always
